### ISSUE TITLE
Error running 'dotnet dockerize' : 'Version for package `Brthor.Dockerize.NET` could not be resolved.'

### ISSUE THREAD

**Issue by jochenvanwylick** [brthor/Dockerize.NET#9] opened 2018-04-13 11:30 UTC
Reproduction steps:
`dotnet new webapi`

Updated .csproj file with
```
  <ItemGroup>
    <DotNetCliToolReference Include="Brthor.Dockerize.NET" Version="1.0.0-*" />
  </ItemGroup>
```

Run
`dotnet dockerize` 

Result
![image](https://user-images.githubusercontent.com/3002474/38732476-8bf53db8-3f1e-11e8-8888-e07753d5951d.png)

**Comment by brthor** [comment] 2018-04-13 20:50
Hey thanks for the report.
I am actually not able to reproduce this locally (but I'm on a mac). 

Can you show me the output of `dotnet --info`?

You may try removing the `bin` and `obj` directories for your project, and then run `dotnet restore` then `dotnet dockerize`. This should fix any potential problems with the restore.

**Comment by brthor** [comment] 2018-07-03 23:18
@jochenvanwylick If all else fails try using the exact version: `1.0.0-beta-00061`

I'm going to close this out but if you still have this problem, comment and I will reopen.

**Closed as completed by brthor** 2018-07-03 23:18 UTC
